services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: akichatting-rabbitmq
    environment:
      - DEFAULT_USER=${RABBITMQ_USER:-admin}
      - DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin}
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379
    container_name: akichatting-redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]