// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/FabricioCosati/go-websocket-rabbitMQ/internal/config"
	"github.com/FabricioCosati/go-websocket-rabbitMQ/internal/handlers"
	"github.com/FabricioCosati/go-websocket-rabbitMQ/internal/services/websocket"
	"github.com/FabricioCosati/go-websocket-rabbitMQ/internal/usecase"
)

// Injectors from wire.go:

func InitApp(cfg config.Config) (*App, error) {
	websocketBrokerServiceImpl := websocket.InitWebsocketBrokerService(cfg)
	websocketClientService := websocket.InitWebsocketClientService()
	websocketUsecaseImpl := usecase.InitWebsocketUsecase(websocketBrokerServiceImpl, websocketClientService)
	websocketHandlerImpl := handlers.InitWebsocketHandler(websocketUsecaseImpl)
	websocketInit := NewWebsocketInit(websocketBrokerServiceImpl, websocketClientService, websocketUsecaseImpl, websocketHandlerImpl)
	app := NewApp(websocketInit)
	return app, nil
}

// wire.go:

type App struct {
	WebsocketInit *WebsocketInit
}

func NewApp(websocketInit *WebsocketInit) *App {
	return &App{
		WebsocketInit: websocketInit,
	}
}
